class Country {
  final String name;
  final String dialCode;
  final String flag;

  const Country({
    required this.name,
    required this.dialCode,
    required this.flag,
  });
}

const List<Country> allCountries = [
  Country(name: 'Afghanistan', dialCode: '+93', flag: '🇦🇫'),
  Country(name: 'Albania', dialCode: '+355', flag: '🇦🇱'),
  Country(name: 'Algeria', dialCode: '+213', flag: '🇩🇿'),
  Country(name: 'Andorra', dialCode: '+376', flag: '🇦🇩'),
  Country(name: 'Angola', dialCode: '+244', flag: '🇦🇴'),
  Country(name: 'Argentina', dialCode: '+54', flag: '🇦🇷'),
  Country(name: 'Armenia', dialCode: '+374', flag: '🇦🇲'),
  Country(name: 'Australia', dialCode: '+61', flag: '🇦🇺'),
  Country(name: 'Austria', dialCode: '+43', flag: '🇦🇹'),
  Country(name: 'Azerbaijan', dialCode: '+994', flag: '🇦🇿'),
  Country(name: 'Bahamas', dialCode: '+1242', flag: '🇧🇸'),
  Country(name: 'Bahrain', dialCode: '+973', flag: '🇧🇭'),
  Country(name: 'Bangladesh', dialCode: '+880', flag: '🇧🇩'),
  Country(name: 'Barbados', dialCode: '+1246', flag: '🇧🇧'),
  Country(name: 'Belarus', dialCode: '+375', flag: '🇧🇾'),
  Country(name: 'Belgium', dialCode: '+32', flag: '🇧🇪'),
  Country(name: 'Belize', dialCode: '+501', flag: '🇧🇿'),
  Country(name: 'Benin', dialCode: '+229', flag: '🇧🇯'),
  Country(name: 'Bhutan', dialCode: '+975', flag: '🇧🇹'),
  Country(name: 'Bolivia', dialCode: '+591', flag: '🇧🇴'),
  Country(name: 'Bosnia and Herzegovina', dialCode: '+387', flag: '🇧🇦'),
  Country(name: 'Botswana', dialCode: '+267', flag: '🇧🇼'),
  Country(name: 'Brazil', dialCode: '+55', flag: '🇧🇷'),
  Country(name: 'Brunei', dialCode: '+673', flag: '🇧🇳'),
  Country(name: 'Bulgaria', dialCode: '+359', flag: '🇧🇬'),
  Country(name: 'Burkina Faso', dialCode: '+226', flag: '🇧🇫'),
  Country(name: 'Burundi', dialCode: '+257', flag: '🇧🇮'),
  Country(name: 'Cambodia', dialCode: '+855', flag: '🇰🇭'),
  Country(name: 'Cameroon', dialCode: '+237', flag: '🇨🇲'),
  Country(name: 'Canada', dialCode: '+1', flag: '🇨🇦'),
  Country(name: 'Cape Verde', dialCode: '+238', flag: '🇨🇻'),
  Country(name: 'Central African Republic', dialCode: '+236', flag: '🇨🇫'),
  Country(name: 'Chad', dialCode: '+235', flag: '🇹🇩'),
  Country(name: 'Chile', dialCode: '+56', flag: '🇨🇱'),
  Country(name: 'China', dialCode: '+86', flag: '🇨🇳'),
  Country(name: 'Colombia', dialCode: '+57', flag: '🇨🇴'),
  Country(name: 'Comoros', dialCode: '+269', flag: '🇰🇲'),
  Country(name: 'Congo', dialCode: '+242', flag: '🇨🇬'),
  Country(name: 'Costa Rica', dialCode: '+506', flag: '🇨🇷'),
  Country(name: 'Croatia', dialCode: '+385', flag: '🇭🇷'),
  Country(name: 'Cuba', dialCode: '+53', flag: '🇨🇺'),
  Country(name: 'Cyprus', dialCode: '+357', flag: '🇨🇾'),
  Country(name: 'Czech Republic', dialCode: '+420', flag: '🇨🇿'),
  Country(name: 'Denmark', dialCode: '+45', flag: '🇩🇰'),
  Country(name: 'Djibouti', dialCode: '+253', flag: '🇩🇯'),
  Country(name: 'Dominican Republic', dialCode: '+1809', flag: '🇩🇴'),
  Country(name: 'Ecuador', dialCode: '+593', flag: '🇪🇨'),
  Country(name: 'Egypt', dialCode: '+20', flag: '🇪🇬'),
  Country(name: 'El Salvador', dialCode: '+503', flag: '🇸🇻'),
  Country(name: 'Estonia', dialCode: '+372', flag: '🇪🇪'),
  Country(name: 'Ethiopia', dialCode: '+251', flag: '🇪🇹'),
  Country(name: 'Fiji', dialCode: '+679', flag: '🇫🇯'),
  Country(name: 'Finland', dialCode: '+358', flag: '🇫🇮'),
  Country(name: 'France', dialCode: '+33', flag: '🇫🇷'),
  Country(name: 'Georgia', dialCode: '+995', flag: '🇬🇪'),
  Country(name: 'Germany', dialCode: '+49', flag: '🇩🇪'),
  Country(name: 'Ghana', dialCode: '+233', flag: '🇬🇭'),
  Country(name: 'Greece', dialCode: '+30', flag: '🇬🇷'),
  Country(name: 'Guatemala', dialCode: '+502', flag: '🇬🇹'),
  Country(name: 'Honduras', dialCode: '+504', flag: '🇭🇳'),
  Country(name: 'Hong Kong', dialCode: '+852', flag: '🇭🇰'),
  Country(name: 'Hungary', dialCode: '+36', flag: '🇭🇺'),
  Country(name: 'Iceland', dialCode: '+354', flag: '🇮🇸'),
  Country(name: 'India', dialCode: '+91', flag: '🇮🇳'),
  Country(name: 'Indonesia', dialCode: '+62', flag: '🇮🇩'),
  Country(name: 'Iran', dialCode: '+98', flag: '🇮🇷'),
  Country(name: 'Iraq', dialCode: '+964', flag: '🇮🇶'),
  Country(name: 'Ireland', dialCode: '+353', flag: '🇮🇪'),
  Country(name: 'Israel', dialCode: '+972', flag: '🇮🇱'),
  Country(name: 'Italy', dialCode: '+39', flag: '🇮🇹'),
  Country(name: 'Jamaica', dialCode: '+1876', flag: '🇯🇲'),
  Country(name: 'Japan', dialCode: '+81', flag: '🇯🇵'),
  Country(name: 'Jordan', dialCode: '+962', flag: '🇯🇴'),
  Country(name: 'Kazakhstan', dialCode: '+7', flag: '🇰🇿'),
  Country(name: 'Kenya', dialCode: '+254', flag: '🇰🇪'),
  Country(name: 'Kuwait', dialCode: '+965', flag: '🇰🇼'),
  Country(name: 'Laos', dialCode: '+856', flag: '🇱🇦'),
  Country(name: 'Lebanon', dialCode: '+961', flag: '🇱🇧'),
  Country(name: 'Libya', dialCode: '+218', flag: '🇱🇾'),
  Country(name: 'Luxembourg', dialCode: '+352', flag: '🇱🇺'),
  Country(name: 'Macau', dialCode: '+853', flag: '🇲🇴'),
  Country(name: 'Malaysia', dialCode: '+60', flag: '🇲🇾'),
  Country(name: 'Maldives', dialCode: '+960', flag: '🇲🇻'),
  Country(name: 'Mexico', dialCode: '+52', flag: '🇲🇽'),
  Country(name: 'Monaco', dialCode: '+377', flag: '🇲🇨'),
  Country(name: 'Mongolia', dialCode: '+976', flag: '🇲🇳'),
  Country(name: 'Morocco', dialCode: '+212', flag: '🇲🇦'),
  Country(name: 'Myanmar', dialCode: '+95', flag: '🇲🇲'),
  Country(name: 'Nepal', dialCode: '+977', flag: '🇳🇵'),
  Country(name: 'Netherlands', dialCode: '+31', flag: '🇳🇱'),
  Country(name: 'New Zealand', dialCode: '+64', flag: '🇳🇿'),
  Country(name: 'Nigeria', dialCode: '+234', flag: '🇳🇬'),
  Country(name: 'North Korea', dialCode: '+850', flag: '🇰🇵'),
  Country(name: 'Norway', dialCode: '+47', flag: '🇳🇴'),
  Country(name: 'Oman', dialCode: '+968', flag: '🇴🇲'),
  Country(name: 'Pakistan', dialCode: '+92', flag: '🇵🇰'),
  Country(name: 'Palestine', dialCode: '+970', flag: '🇵🇸'),
  Country(name: 'Panama', dialCode: '+507', flag: '🇵🇦'),
  Country(name: 'Papua New Guinea', dialCode: '+675', flag: '🇵🇬'),
  Country(name: 'Paraguay', dialCode: '+595', flag: '🇵🇾'),
  Country(name: 'Peru', dialCode: '+51', flag: '🇵🇪'),
  Country(name: 'Philippines', dialCode: '+63', flag: '🇵🇭'),
  Country(name: 'Poland', dialCode: '+48', flag: '🇵🇱'),
  Country(name: 'Portugal', dialCode: '+351', flag: '🇵🇹'),
  Country(name: 'Qatar', dialCode: '+974', flag: '🇶🇦'),
  Country(name: 'Romania', dialCode: '+40', flag: '🇷🇴'),
  Country(name: 'Russia', dialCode: '+7', flag: '🇷🇺'),
  Country(name: 'Saudi Arabia', dialCode: '+966', flag: '🇸🇦'),
  Country(name: 'Senegal', dialCode: '+221', flag: '🇸🇳'),
  Country(name: 'Serbia', dialCode: '+381', flag: '🇷🇸'),
  Country(name: 'Singapore', dialCode: '+65', flag: '🇸🇬'),
  Country(name: 'Slovakia', dialCode: '+421', flag: '🇸🇰'),
  Country(name: 'Slovenia', dialCode: '+386', flag: '🇸🇮'),
  Country(name: 'South Africa', dialCode: '+27', flag: '🇿🇦'),
  Country(name: 'South Korea', dialCode: '+82', flag: '🇰🇷'),
  Country(name: 'Spain', dialCode: '+34', flag: '🇪🇸'),
  Country(name: 'Sri Lanka', dialCode: '+94', flag: '🇱🇰'),
  Country(name: 'Sweden', dialCode: '+46', flag: '🇸🇪'),
  Country(name: 'Switzerland', dialCode: '+41', flag: '🇨🇭'),
  Country(name: 'Taiwan', dialCode: '+886', flag: '🇹🇼'),
  Country(name: 'Thailand', dialCode: '+66', flag: '🇹🇭'),
  Country(name: 'Timor-Leste', dialCode: '+670', flag: '🇹🇱'),
  Country(name: 'Turkey', dialCode: '+90', flag: '🇹🇷'),
  Country(name: 'Ukraine', dialCode: '+380', flag: '🇺🇦'),
  Country(name: 'United Arab Emirates', dialCode: '+971', flag: '🇦🇪'),
  Country(name: 'United Kingdom', dialCode: '+44', flag: '🇬🇧'),
  Country(name: 'United States', dialCode: '+1', flag: '🇺🇸'),
  Country(name: 'Uruguay', dialCode: '+598', flag: '🇺🇾'),
  Country(name: 'Uzbekistan', dialCode: '+998', flag: '🇺🇿'),
  Country(name: 'Vatican City', dialCode: '+379', flag: '🇻🇦'),
  Country(name: 'Venezuela', dialCode: '+58', flag: '🇻🇪'),
  Country(name: 'Vietnam', dialCode: '+84', flag: '🇻🇳'),
  Country(name: 'Yemen', dialCode: '+967', flag: '🇾🇪'),
  Country(name: 'Zimbabwe', dialCode: '+263', flag: '🇿🇼'),
];